services:
  db:
    image: "mysql:8.4"
    restart: "unless-stopped"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - "./.sql_data:/var/lib/mysql"
    ports:
      - "33060:3306"
  phpmyadmin:
    image: "phpmyadmin:5.2.1-apache"
    restart: "unless-stopped"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
